// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHwX-QfxsUteNHg3B4h9U8XwSzontfr6E',
    appId: '1:701458994677:web:3dd9e131e24ab2270abcbc',
    messagingSenderId: '701458994677',
    projectId: 'notes-cad56',
    authDomain: 'notes-cad56.firebaseapp.com',
    storageBucket: 'notes-cad56.appspot.com',
    measurementId: 'G-ENP2N8QKVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmLm20GbNC9Xlfe0F_ICVWVvKFMbo9OF8',
    appId: '1:701458994677:android:e1c4e075949e36d30abcbc',
    messagingSenderId: '701458994677',
    projectId: 'notes-cad56',
    storageBucket: 'notes-cad56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDabNGFkPYOvnDiprghML9FxgicvFJ7NKg',
    appId: '1:701458994677:ios:ad68d40293aedcec0abcbc',
    messagingSenderId: '701458994677',
    projectId: 'notes-cad56',
    storageBucket: 'notes-cad56.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDabNGFkPYOvnDiprghML9FxgicvFJ7NKg',
    appId: '1:701458994677:ios:ad68d40293aedcec0abcbc',
    messagingSenderId: '701458994677',
    projectId: 'notes-cad56',
    storageBucket: 'notes-cad56.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHwX-QfxsUteNHg3B4h9U8XwSzontfr6E',
    appId: '1:701458994677:web:b63037399614a62e0abcbc',
    messagingSenderId: '701458994677',
    projectId: 'notes-cad56',
    authDomain: 'notes-cad56.firebaseapp.com',
    storageBucket: 'notes-cad56.appspot.com',
    measurementId: 'G-9T29K82942',
  );

}